captainVersion: 4
services:
    $$cap_appname:
        image: libretranslate/libretranslate:$$cap_libretranslate_version
        volumes:
            - $$cap_appname-data:/home/libretranslate/.local
        restart: always
        environment:
            LT_HOST: 0.0.0.0
            LT_PORT: 5000
            LT_CHAR_LIMIT: $$cap_char_limit
            LT_REQ_LIMIT: $$cap_req_limit
            LT_API_KEYS: $$cap_api_keys_enabled
            LT_FRONTEND_LANGUAGE_SOURCE: auto
            LT_FRONTEND_LANGUAGE_TARGET: en
            LT_FRONTEND_TIMEOUT: 500
            LT_SUGGESTIONS: $$cap_suggestions_enabled
            LT_DISABLE_FILES_TRANSLATION: $$cap_disable_files
            LT_LOAD_ONLY: $$cap_load_only_languages
            LT_UPDATE_MODELS: $$cap_update_models
        caproverExtra:
            containerHttpPort: '5000'
caproverOneClickApp:
    variables:
        - id: $$cap_libretranslate_version
          label: LibreTranslate Version
          description: Check available versions at https://hub.docker.com/r/libretranslate/libretranslate/tags
          defaultValue: v1.7.2
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_char_limit
          label: Character Limit
          description: Set character limit per request (-1 for no limit)
          defaultValue: '5000'
          validRegex: /^-?\d+$/
        - id: $$cap_req_limit
          label: Request Limit (per minute)
          description: Set maximum requests per minute (-1 for no limit)
          defaultValue: '-1'
          validRegex: /^-?\d+$/
        - id: $$cap_api_keys_enabled
          label: Enable API Keys
          description: Enable API key database for authentication
          defaultValue: 'false'
          validRegex: /^(true|false)$/
        - id: $$cap_suggestions_enabled
          label: Enable Translation Suggestions
          description: Allow users to submit translation suggestions
          defaultValue: 'false'
          validRegex: /^(true|false)$/
        - id: $$cap_disable_files
          label: Disable File Translation
          description: Disable file translation feature
          defaultValue: 'false'
          validRegex: /^(true|false)$/
        - id: $$cap_load_only_languages
          label: Load Only Languages
          description: Comma-separated language codes to load (e.g., en,fr,tr,ar). Leave empty to load all languages.
          defaultValue: 'en,fr,tr,ar'
        - id: $$cap_update_models
          label: Update Models on Startup
          description: Download/update language models on startup (set to false after first deployment)
          defaultValue: 'true'
          validRegex: /^(true|false)$/
    instructions:
        start: |-
            LibreTranslate - Free and Open Source Machine Translation API
            
            This deployment includes:
            • Self-hosted translation API
            • Web UI for translations
            • Support for 100+ languages
            • Offline capable
            • API key support (optional)
            • File translation support
            
            Note: Language models will be downloaded on first start (may take several minutes).
        end: |-
            ✅ LibreTranslate has been deployed successfully!
            --------------------------------------------
            
            🌐 Access URL: https://$$cap_appname.$$cap_root_domain
            
            📝 Important Notes:
            • First startup will download language models (this may take 5-10 minutes)
            • Enable HTTPS in CapRover for secure API usage
            • Models are stored persistently in the volume
            
            ⚙️ Configuration:
            • Character Limit: $$cap_char_limit characters per request
            • Request Limit: $$cap_req_limit requests per minute
            • API Keys: $$cap_api_keys_enabled
            • Suggestions: $$cap_suggestions_enabled
            • File Translation: Enabled (unless disabled)
            
            🔑 API Usage:
            • Web UI: https://$$cap_appname.$$cap_root_domain
            • API Endpoint: https://$$cap_appname.$$cap_root_domain/translate
            • API Docs: https://$$cap_appname.$$cap_root_domain/docs
            
            📦 Language Models:
            • Initial languages: $$cap_load_only_languages
            • Models are cached in: /home/libretranslate/.local
            • To add more languages later, edit LT_LOAD_ONLY in environment variables
            • Set LT_UPDATE_MODELS=true to download new languages, then set back to false
            
            🔐 API Keys (if enabled):
            • Manage keys using: docker exec -it $(docker ps -qf name=$$cap_appname) ltmanage keys add <req-limit>
            • Example: docker exec -it <container-id> ltmanage keys add 120
            
            📖 Documentation: https://github.com/LibreTranslate/LibreTranslate
            🌐 Website: https://libretranslate.com
    displayName: LibreTranslate
    isOfficial: false
    description: Free and Open Source Machine Translation API. Self-hosted, offline capable, and easy to setup.
    documentation: 'See more at: https://github.com/LibreTranslate/LibreTranslate'
    logoUrl: https://raw.githubusercontent.com/caprover/one-click-apps/master/public/v4/logos/libretranslate.png
