captainVersion: 4
services:
    $$cap_appname:
        image: devlikeapro/waha:$$cap_waha_version
        volumes:
            - $$cap_appname-data:/app/.sessions
            - $$cap_appname-media:/tmp/whatsapp-files
        environment:
            WHATSAPP_API_PORT: '3000'
            TZ: $$cap_timezone
            WAHA_LOG_FORMAT: $$cap_log_format
            WAHA_LOG_LEVEL: $$cap_log_level
            WHATSAPP_DEFAULT_ENGINE: $$cap_default_engine
            WAHA_PRINT_QR: $$cap_print_qr
            WHATSAPP_RESTART_ALL_SESSIONS: $$cap_restart_all_sessions
            WAHA_API_KEY: $$cap_api_key
        caproverExtra:
            containerHttpPort: '3000'
caproverOneClickApp:
    variables:
        - id: $$cap_waha_version
          label: WAHA Version
          description: Check out their Docker page for valid tags https://hub.docker.com/r/devlikeapro/waha/tags
          defaultValue: 'latest-2025.12.1'
          validRegex: /^([^\s^\/])+$/

        - id: $$cap_timezone
          label: Timezone
          description: Set your timezone (e.g., Europe/London, America/New_York, Asia/Tokyo). Find your timezone at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
          defaultValue: 'UTC'

        - id: $$cap_log_format
          label: Log Format
          description: Log output format
          defaultValue: 'PRETTY'
          validRegex: /^(PRETTY|JSON)$/

        - id: $$cap_log_level
          label: Log Level
          description: How much information to log (do not use debug/trace in production)
          defaultValue: 'info'
          validRegex: /^(error|warn|info|debug|trace)$/

        - id: $$cap_default_engine
          label: Default Engine
          description: WhatsApp engine to use (WEBJS=browser-based, NOWEB=websocket nodejs, GOWS=websocket go)
          defaultValue: 'WEBJS'
          validRegex: /^(WEBJS|NOWEB|GOWS)$/

        - id: $$cap_print_qr
          label: Print QR to Console
          description: Enable printing QR codes to console logs
          defaultValue: 'True'
          validRegex: /^(True|False)$/

        - id: $$cap_restart_all_sessions
          label: Restart All Sessions on Boot
          description: Automatically restart all STOPPED sessions after container restart
          defaultValue: 'False'
          validRegex: /^(True|False)$/

        - id: $$cap_api_key
          label: API Key (Optional)
          description: Secure your API with X-Api-Key header. Leave empty for no authentication (not recommended for production). Use a long random string.
          defaultValue: ''
    instructions:
        start: |-
            WAHA - WhatsApp HTTP API (REST API) that you can configure in a click!

            A self-hosted WhatsApp API that allows you to send and receive messages, manage sessions, and automate WhatsApp interactions via HTTP REST API.

            Features:
            • Send/receive text, media, voice messages
            • QR code authentication
            • Multiple sessions support (Plus version)
            • Webhooks for real-time events
            • 3 engines: WEBJS (browser), NOWEB (nodejs websocket), GOWS (go websocket)
        end: |-
            ✅ WAHA has been deployed successfully!
            --------------------------------------------

            Access your WAHA instance at: http://$$cap_appname.$$cap_root_domain

            📚 Documentation: http://$$cap_appname.$$cap_root_domain (Swagger UI)
            📊 Dashboard: http://$$cap_appname.$$cap_root_domain/dashboard

            🚀 Quick Start:
            1. Open the Swagger UI at your instance URL
            2. Create a new session: POST /api/sessions with {"name": "default"}
            3. Get QR code: GET /api/screenshot
            4. Scan QR with your WhatsApp mobile app
            5. Send messages: POST /api/sendText

            ⚠️ Important Notes:
            • Enable HTTPS in CapRover for production use
            • Set an API Key for security (via environment variables)
            • Sessions and media files are persisted in volumes
            • For multiple sessions, consider WAHA Plus version

            📖 Full Documentation: https://waha.devlike.pro/docs/
    displayName: WAHA
    isOfficial: true
    description: WhatsApp HTTP API - Self-hosted WhatsApp REST API for sending/receiving messages and automation
    documentation: https://waha.devlike.pro/docs/overview/introduction/
